In [16]:
# Generate ANDNOT function using McCulloch-Pitts neural net by a python program. 

In [24]:
'''
Expected AND NOT output :
x1  x2  x2' output
0   0   1    0
0   1   0    0
1   0   1    1
1   1   0    0
'''

'''
x1 w1 x2 w2  (x1w1)  (x2w2)  (sum)  (T(1))  
0  1  0  -1    0       0       0      0
0  1  1  -1    0      -1      -1      0
1  1  0  -1    1       0       1      1
1  1  1  -1    1      -1       0      0


x1 x2        
0  0        1  w1
0  1       -1  w2
1  0
1  1
'''

'\nx1 w1 x2 w2  (x1w1)  (x2w2)  (sum)  (T(1))  \n0  1  0  -1    0       0       0      0\n0  1  1  -1    0      -1      -1      0\n1  1  0  -1    1       0       1      1\n1  1  1  -1    1      -1       0      0\n\n\nx1 x2        \n0  0        1  w1\n0  1       -1  w2\n1  0\n1  1\n'

In [25]:
import numpy as np

In [26]:
# function of checking thresold value 
def linear_threshold_gate(dot, T):
    if dot >= T:
        return 1 
    else:
        return 0

In [27]:
# matrix of inputs 
input_table = np.array([
    [0,0], # both no
    [0,1], # one no, one yes 
    [1,0], # one yes, one no 
    [1,1]  # bot yes
])

weights = np.array([1,-1])
T = 1

In [28]:
dot_products_sum = input_table @ weights

In [29]:
print(f'input table:\n{input_table}\n')
print(f'dot products:\n{dot_products_sum}')

input table:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

dot products:
[ 0 -1  1  0]


In [30]:
for i in range (0,4):
    activation = linear_threshold_gate(dot_products_sum[i], T)
    print(f'Activation:{activation}')

Activation:0
Activation:0
Activation:1
Activation:0


In [23]:
import numpy as np

In [24]:
inputs = np.array([
    [0,0],[0,1],[1,0],[1,1]
])

weight = [1,-1]

T = 1

In [25]:
dot_product = inputs @ weight

In [26]:
print(f'input table:\n{inputs}\n')
print(f'dot products:\n{dot_product}')

input table:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

dot products:
[ 0 -1  1  0]


In [27]:
def linear_threshold_gate(dot, T):
    if dot >= T:
        return 1
    else:
        return 0

In [30]:
for i in range(0,4):
    #acctivation = linear_threshold_gate(dot_products[i], T)
    print('acctivation : ', linear_threshold_gate(dot_product[i], T))

acctivation :  0
acctivation :  0
acctivation :  1
acctivation :  0


In [19]:
import numpy as np

In [20]:
inputs = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

weights = np.array([1, -1])

t = 1

In [21]:
dot_product = inputs @ weights

In [22]:
def linear_threshold_gate(dot_product,t):
    if dot_product >= t:
        return 1
    else:
        return 0

In [24]:
for i in range(0,4):
    print("activation : ",linear_threshold_gate(dot_product[i], t))

activation :  0
activation :  0
activation :  1
activation :  0
